### ISSUE TITLE
[Bug]: panic in Corso

### ISSUE THREAD

**Issue by ntolia** [alcionai/corso#2529]
### What happened?

This is likely invalid configuration on my end. Will narrow that down but Corso should not panic with invalid config.

### Corso Version?

Corso v0.3.0

### Where are you running Corso?

Docker, macOS, arm64

### Relevant log output

```shell
Connecting to repository:      …
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x87b054]

goroutine 1514 [running]:
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).fetchBlobInternal(0x4005a720c0, {0x3e52318, 0x40008880c0}, {0x4000057d00, 0x36}, 0x400076e2e1?)
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/internal/cache/content_cache.go:105 +0x74
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).getContentFromFullBlob(0x4005a720c0, {0x3e52318, 0x40008880c0}, {0x4000057d00, 0x36}, 0x20, 0x294, 0x0?)
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/internal/cache/content_cache.go:76 +0x144
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).GetContent(0x3e59d50?, {0x3e52318?, 0x40008880c0?}, {0x4005de9da0?, 0x106d?}, {0x4000057d00?, 0x4000696a58?}, 0x3e59d50?, 0x4005b9efa0?, 0x0?)
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/internal/cache/content_cache.go:56 +0x48
github.com/kopia/kopia/repo/content.(*SharedManager).getContentDataReadLocked(0x400017e000, {0x3e52318, 0x40008880c0}, 0x0, {0x3e59d50, 0x4005b9efa0}, 0x3e52318?)
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/content/content_manager_lock_free.go:117 +0x29c
github.com/kopia/kopia/repo/content.(*WriteManager).getContentDataAndInfo(0x4000831ce0, {0x3e52318, 0x40008880c0}, {{0x7f, 0x34, 0xf9, 0x28, 0x39, 0x9e, 0x6e, ...}, ...}, ...)
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/content/content_manager.go:667 +0x128
github.com/kopia/kopia/repo/content.(*WriteManager).GetContent(0x4000831ce0, {0x3e52318, 0x40008880c0}, {{0x7f, 0x34, 0xf9, 0x28, 0x39, 0x9e, 0x6e, ...}, ...})
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/content/content_manager.go:854 +0x108
github.com/kopia/kopia/repo/manifest.loadManifestContent({0x3e52318, 0x40008880c0}, {0x3e57450, 0x4000831ce0}, {{0x7f, 0x34, 0xf9, 0x28, 0x39, 0x9e, ...}, ...})
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/manifest/committed_manifest_manager.go:339 +0x80
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).loadCommittedContentsLocked.func1({0x3e59d50, 0x40058baaa0})
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/manifest/committed_manifest_manager.go:146 +0xc8
github.com/kopia/kopia/repo/content.maybeParallelExecutor.func5()
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/content/content_manager_iterate.go:74 +0x90
created by github.com/kopia/kopia/repo/content.maybeParallelExecutor
	/go/pkg/mod/github.com/kopia/kopia@v0.12.2-0.20230123092305-e5387cec0acb/repo/content/content_manager_iterate.go:70 +0x1b8
```

**Comment by ntolia** [comment]
This is likely an Alpine and Go 1.19 issue and not a Corso issue.

**Comment by meain** [comment]
I still don't have a solution for this, but here are a few things that don't work:
- Statically linking binaries (alpine and ubuntu)
- Building using `golang` image and running via `ubuntu`
- Building using `golang:1.19` and running via `ubuntu:22.04`
- [Stripping or omitting drwaf symbols](https://pkg.go.dev/cmd/link)  (was worth a shot)

**Comment by ntolia** [comment]
@meain I will add that if I bring in the natively built binaries into the container images, things work!

**Comment by ntolia** [comment]
This panic will happen whenever `KOPIA_CACHE_DIRECTORY` is set, independent of whether Corso is running inside or outside of containers.
