### ISSUE TITLE
[Bug]: Segmentation violation when listing backups during initial backup

### ISSUE THREAD

**Issue by Integratinator** [alcionai/corso#5069]
### What happened?

When an initial backup is running, listing the backups results in a segmentation violation.
The two commands that are run:
- corso backup create onedrive --user '*' --log-file ./logs/onedrive.log --config-file ./toml/onedrive.toml --hide-progress
- corso backup list onedrive --config-file ./toml/onedrive.toml

### Corso Version?

Corso v0.17.0

### Where are you running Corso?

Running the two commands in different terminals on the same host, an Ubuntu VM with 4 cores and 64GB RAM.

### Relevant log output

```shell
Connecting to M365                               done 
Connecting to repository                      4s done 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x316fb09]

goroutine 499 [running]:
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).fetchBlobInternal(0xc0007900c0, {0x555af80, 0xc00063d620}, {0xc0045972c0, 0x36}, 0x7caecf8?)
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/internal/cache/content_cache.go:105 +0x149
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).getContentFromFullBlob(0xc0007900c0, {0x555af80, 0xc00063d620}, {0xc0045972c0, 0x36}, 0x20, 0x317, 0x0?)
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/internal/cache/content_cache.go:76 +0x1f2
github.com/kopia/kopia/internal/cache.(*contentCacheImpl).GetContent(0x36?, {0x555af80?, 0xc00063d620?}, {0xc001505aa0?, 0x963577977218508?}, {0xc0045972c0?, 0x0?}, 0x0?, 0x300106d?, 0xc000f3a9c0)
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/internal/cache/content_cache.go:58 +0x45
github.com/kopia/kopia/repo/content.(*SharedManager).getContentDataReadLocked(0xc000002000, {0x555af80, 0xc00063d620}, 0x0, {{0xc0045972c0, 0x36}, 0x65a79ea7, 0x2fb, 0x317, 0x20, ...}, ...)
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/content/content_manager_lock_free.go:117 +0x2c3
github.com/kopia/kopia/repo/content.(*WriteManager).getContentDataAndInfo(0xc0001f02c0, {0x555af80, 0xc00063d620}, {{0x8, 0x85, 0x21, 0x77, 0x79, 0x57, 0x63, ...}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/content/content_manager.go:666 +0x1f6
github.com/kopia/kopia/repo/content.(*WriteManager).GetContent(0xc0001f02c0, {0x555af80, 0xc00063d620}, {{0x8, 0x85, 0x21, 0x77, 0x79, 0x57, 0x63, ...}, ...})
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/content/content_manager.go:853 +0x1b9
github.com/kopia/kopia/repo/manifest.loadManifestContent({0x555af80?, 0xc00063d620?}, {0x5563e00?, 0xc0001f02c0?}, {{0x8, 0x85, 0x21, 0x77, 0x79, 0x57, ...}, ...})
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/manifest/committed_manifest_manager.go:346 +0x9c
github.com/kopia/kopia/repo/manifest.(*committedManifestManager).loadCommittedContentsLocked.func1({{0xc004590e40, 0x36}, 0x65a79ea7, 0x2fb, 0x317, 0x20, 0x0, {{0x8, 0x85, 0x21, ...}, ...}, ...})
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/manifest/committed_manifest_manager.go:151 +0xa5
github.com/kopia/kopia/repo/content.maybeParallelExecutor.func5()
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/content/content_manager_iterate.go:74 +0x11b
created by github.com/kopia/kopia/repo/content.maybeParallelExecutor in goroutine 1
	/home/runner/go/pkg/mod/github.com/alcionai/kopia@v0.12.2-0.20231205231702-863c24d6f8b1/repo/content/content_manager_iterate.go:70 +0x197
```

**Comment by Integratinator** [comment]
KOPIA_CACHE_DIRECTORY is not set. I am however running two initial backups on the same host (different terminals).  One backup is an exchange, the other is onedrive. They use the same bucket, but with different prefix. Is it possible that the /tmp/repository.config files might be clashing?

**Comment by vkamra** [comment]
Stack is similar(identical?) to #2529. Linking that here as well.
